// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: platform/tenant_service/v1/tenant.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTenantCheckQuota = "/platform.tenant_service.v1.Tenant/CheckQuota"
const OperationTenantConsumeQuota = "/platform.tenant_service.v1.Tenant/ConsumeQuota"
const OperationTenantCreateTenant = "/platform.tenant_service.v1.Tenant/CreateTenant"
const OperationTenantDeleteTenant = "/platform.tenant_service.v1.Tenant/DeleteTenant"
const OperationTenantGetTenant = "/platform.tenant_service.v1.Tenant/GetTenant"
const OperationTenantListProducts = "/platform.tenant_service.v1.Tenant/ListProducts"
const OperationTenantListTenants = "/platform.tenant_service.v1.Tenant/ListTenants"
const OperationTenantReleaseQuota = "/platform.tenant_service.v1.Tenant/ReleaseQuota"
const OperationTenantUpdateTenant = "/platform.tenant_service.v1.Tenant/UpdateTenant"

type TenantHTTPServer interface {
	// CheckQuota CheckQuota 检查配额
	CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaReply, error)
	// ConsumeQuota ConsumeQuota 消费配额
	ConsumeQuota(context.Context, *ConsumeQuotaRequest) (*ConsumeQuotaReply, error)
	// CreateTenant CreateTenant 创建租户
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantReply, error)
	// DeleteTenant DeleteTenant 删除租户
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantReply, error)
	// GetTenant GetTenant 获取租户信息
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantReply, error)
	// ListProducts ListProducts 列出产品线
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	// ListTenants ListTenants 列出租户
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsReply, error)
	// ReleaseQuota ReleaseQuota 释放配额
	ReleaseQuota(context.Context, *ReleaseQuotaRequest) (*ReleaseQuotaReply, error)
	// UpdateTenant UpdateTenant 更新租户
	UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantReply, error)
}

func RegisterTenantHTTPServer(s *http.Server, srv TenantHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/tenants", _Tenant_CreateTenant0_HTTP_Handler(srv))
	r.GET("/v1/tenants/{tenant_id}", _Tenant_GetTenant0_HTTP_Handler(srv))
	r.GET("/v1/tenants", _Tenant_ListTenants0_HTTP_Handler(srv))
	r.PUT("/v1/tenants/{tenant_id}", _Tenant_UpdateTenant0_HTTP_Handler(srv))
	r.DELETE("/v1/tenants/{tenant_id}", _Tenant_DeleteTenant0_HTTP_Handler(srv))
	r.POST("/v1/tenants/{tenant_id}/quota/check", _Tenant_CheckQuota0_HTTP_Handler(srv))
	r.POST("/v1/tenants/{tenant_id}/quota/consume", _Tenant_ConsumeQuota0_HTTP_Handler(srv))
	r.POST("/v1/tenants/{tenant_id}/quota/release", _Tenant_ReleaseQuota0_HTTP_Handler(srv))
	r.GET("/v1/products", _Tenant_ListProducts0_HTTP_Handler(srv))
}

func _Tenant_CreateTenant0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantCreateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenant(ctx, req.(*CreateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTenantReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_GetTenant0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantGetTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenant(ctx, req.(*GetTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTenantReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_ListTenants0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTenantsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantListTenants)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTenants(ctx, req.(*ListTenantsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTenantsReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_UpdateTenant0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantUpdateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTenant(ctx, req.(*UpdateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTenantReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_DeleteTenant0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantDeleteTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTenant(ctx, req.(*DeleteTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTenantReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_CheckQuota0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckQuotaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantCheckQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckQuota(ctx, req.(*CheckQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckQuotaReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_ConsumeQuota0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConsumeQuotaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantConsumeQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConsumeQuota(ctx, req.(*ConsumeQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConsumeQuotaReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_ReleaseQuota0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReleaseQuotaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantReleaseQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReleaseQuota(ctx, req.(*ReleaseQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReleaseQuotaReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_ListProducts0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

type TenantHTTPClient interface {
	CheckQuota(ctx context.Context, req *CheckQuotaRequest, opts ...http.CallOption) (rsp *CheckQuotaReply, err error)
	ConsumeQuota(ctx context.Context, req *ConsumeQuotaRequest, opts ...http.CallOption) (rsp *ConsumeQuotaReply, err error)
	CreateTenant(ctx context.Context, req *CreateTenantRequest, opts ...http.CallOption) (rsp *CreateTenantReply, err error)
	DeleteTenant(ctx context.Context, req *DeleteTenantRequest, opts ...http.CallOption) (rsp *DeleteTenantReply, err error)
	GetTenant(ctx context.Context, req *GetTenantRequest, opts ...http.CallOption) (rsp *GetTenantReply, err error)
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	ListTenants(ctx context.Context, req *ListTenantsRequest, opts ...http.CallOption) (rsp *ListTenantsReply, err error)
	ReleaseQuota(ctx context.Context, req *ReleaseQuotaRequest, opts ...http.CallOption) (rsp *ReleaseQuotaReply, err error)
	UpdateTenant(ctx context.Context, req *UpdateTenantRequest, opts ...http.CallOption) (rsp *UpdateTenantReply, err error)
}

type TenantHTTPClientImpl struct {
	cc *http.Client
}

func NewTenantHTTPClient(client *http.Client) TenantHTTPClient {
	return &TenantHTTPClientImpl{client}
}

func (c *TenantHTTPClientImpl) CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...http.CallOption) (*CheckQuotaReply, error) {
	var out CheckQuotaReply
	pattern := "/v1/tenants/{tenant_id}/quota/check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantCheckQuota))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) ConsumeQuota(ctx context.Context, in *ConsumeQuotaRequest, opts ...http.CallOption) (*ConsumeQuotaReply, error) {
	var out ConsumeQuotaReply
	pattern := "/v1/tenants/{tenant_id}/quota/consume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantConsumeQuota))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...http.CallOption) (*CreateTenantReply, error) {
	var out CreateTenantReply
	pattern := "/v1/tenants"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantCreateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...http.CallOption) (*DeleteTenantReply, error) {
	var out DeleteTenantReply
	pattern := "/v1/tenants/{tenant_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantDeleteTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...http.CallOption) (*GetTenantReply, error) {
	var out GetTenantReply
	pattern := "/v1/tenants/{tenant_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantGetTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...http.CallOption) (*ListTenantsReply, error) {
	var out ListTenantsReply
	pattern := "/v1/tenants"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantListTenants))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) ReleaseQuota(ctx context.Context, in *ReleaseQuotaRequest, opts ...http.CallOption) (*ReleaseQuotaReply, error) {
	var out ReleaseQuotaReply
	pattern := "/v1/tenants/{tenant_id}/quota/release"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantReleaseQuota))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TenantHTTPClientImpl) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...http.CallOption) (*UpdateTenantReply, error) {
	var out UpdateTenantReply
	pattern := "/v1/tenants/{tenant_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantUpdateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
