// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: platform/tenant_service/v1/tenant.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "tenant-service/api/base"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 租户类型枚举
type TenantType int32

const (
	TenantType_TENANT_TYPE_UNSPECIFIED TenantType = 0
	TenantType_TENANT_TYPE_PLATFORM    TenantType = 1 // 平台
	TenantType_TENANT_TYPE_CHANNEL     TenantType = 2 // 渠道
	TenantType_TENANT_TYPE_ENTERPRISE  TenantType = 3 // 企业
)

// Enum value maps for TenantType.
var (
	TenantType_name = map[int32]string{
		0: "TENANT_TYPE_UNSPECIFIED",
		1: "TENANT_TYPE_PLATFORM",
		2: "TENANT_TYPE_CHANNEL",
		3: "TENANT_TYPE_ENTERPRISE",
	}
	TenantType_value = map[string]int32{
		"TENANT_TYPE_UNSPECIFIED": 0,
		"TENANT_TYPE_PLATFORM":    1,
		"TENANT_TYPE_CHANNEL":     2,
		"TENANT_TYPE_ENTERPRISE":  3,
	}
)

func (x TenantType) Enum() *TenantType {
	p := new(TenantType)
	*p = x
	return p
}

func (x TenantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_tenant_service_v1_tenant_proto_enumTypes[0].Descriptor()
}

func (TenantType) Type() protoreflect.EnumType {
	return &file_platform_tenant_service_v1_tenant_proto_enumTypes[0]
}

func (x TenantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantType.Descriptor instead.
func (TenantType) EnumDescriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{0}
}

// 配额类型枚举
type QuotaType int32

const (
	QuotaType_QUOTA_TYPE_UNSPECIFIED        QuotaType = 0
	QuotaType_QUOTA_TYPE_MARKETING_CAMPAIGN QuotaType = 1 // 营销活动
	QuotaType_QUOTA_TYPE_REDEEM_CODE        QuotaType = 2 // 兑换码
	QuotaType_QUOTA_TYPE_SMS                QuotaType = 3 // 短信
)

// Enum value maps for QuotaType.
var (
	QuotaType_name = map[int32]string{
		0: "QUOTA_TYPE_UNSPECIFIED",
		1: "QUOTA_TYPE_MARKETING_CAMPAIGN",
		2: "QUOTA_TYPE_REDEEM_CODE",
		3: "QUOTA_TYPE_SMS",
	}
	QuotaType_value = map[string]int32{
		"QUOTA_TYPE_UNSPECIFIED":        0,
		"QUOTA_TYPE_MARKETING_CAMPAIGN": 1,
		"QUOTA_TYPE_REDEEM_CODE":        2,
		"QUOTA_TYPE_SMS":                3,
	}
)

func (x QuotaType) Enum() *QuotaType {
	p := new(QuotaType)
	*p = x
	return p
}

func (x QuotaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_tenant_service_v1_tenant_proto_enumTypes[1].Descriptor()
}

func (QuotaType) Type() protoreflect.EnumType {
	return &file_platform_tenant_service_v1_tenant_proto_enumTypes[1]
}

func (x QuotaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuotaType.Descriptor instead.
func (QuotaType) EnumDescriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{1}
}

// 限制类型枚举
type LimitType int32

const (
	LimitType_LIMIT_TYPE_UNSPECIFIED LimitType = 0
	LimitType_LIMIT_TYPE_DAILY       LimitType = 1 // 每日
	LimitType_LIMIT_TYPE_MONTHLY     LimitType = 2 // 每月
	LimitType_LIMIT_TYPE_TOTAL       LimitType = 3 // 总量
	LimitType_LIMIT_TYPE_CONCURRENT  LimitType = 4 // 并发
)

// Enum value maps for LimitType.
var (
	LimitType_name = map[int32]string{
		0: "LIMIT_TYPE_UNSPECIFIED",
		1: "LIMIT_TYPE_DAILY",
		2: "LIMIT_TYPE_MONTHLY",
		3: "LIMIT_TYPE_TOTAL",
		4: "LIMIT_TYPE_CONCURRENT",
	}
	LimitType_value = map[string]int32{
		"LIMIT_TYPE_UNSPECIFIED": 0,
		"LIMIT_TYPE_DAILY":       1,
		"LIMIT_TYPE_MONTHLY":     2,
		"LIMIT_TYPE_TOTAL":       3,
		"LIMIT_TYPE_CONCURRENT":  4,
	}
)

func (x LimitType) Enum() *LimitType {
	p := new(LimitType)
	*p = x
	return p
}

func (x LimitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_tenant_service_v1_tenant_proto_enumTypes[2].Descriptor()
}

func (LimitType) Type() protoreflect.EnumType {
	return &file_platform_tenant_service_v1_tenant_proto_enumTypes[2]
}

func (x LimitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitType.Descriptor instead.
func (LimitType) EnumDescriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{2}
}

// 操作类型枚举
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_CONSUME     OperationType = 1 // 消费
	OperationType_OPERATION_TYPE_RELEASE     OperationType = 2 // 释放
	OperationType_OPERATION_TYPE_ADJUST      OperationType = 3 // 调整
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_CONSUME",
		2: "OPERATION_TYPE_RELEASE",
		3: "OPERATION_TYPE_ADJUST",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_CONSUME":     1,
		"OPERATION_TYPE_RELEASE":     2,
		"OPERATION_TYPE_ADJUST":      3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_tenant_service_v1_tenant_proto_enumTypes[3].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_platform_tenant_service_v1_tenant_proto_enumTypes[3]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{3}
}

// TenantInfo 租户信息
type TenantInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                                                    // 租户ID
	TenantName     string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`                                                                              // 租户名称
	TenantType     TenantType             `protobuf:"varint,3,opt,name=tenant_type,json=tenantType,proto3,enum=platform.tenant_service.v1.TenantType" json:"tenant_type,omitempty"`                                  // 租户类型
	ParentTenantId string                 `protobuf:"bytes,4,opt,name=parent_tenant_id,json=parentTenantId,proto3" json:"parent_tenant_id,omitempty"`                                                                // 父租户ID
	Status         bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                                                                                       // 状态
	QuotaConfig    map[string]string      `protobuf:"bytes,6,rep,name=quota_config,json=quotaConfig,proto3" json:"quota_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配额配置
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                                                 // 创建时间
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                                                 // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantInfo) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *TenantInfo) GetTenantType() TenantType {
	if x != nil {
		return x.TenantType
	}
	return TenantType_TENANT_TYPE_UNSPECIFIED
}

func (x *TenantInfo) GetParentTenantId() string {
	if x != nil {
		return x.ParentTenantId
	}
	return ""
}

func (x *TenantInfo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TenantInfo) GetQuotaConfig() map[string]string {
	if x != nil {
		return x.QuotaConfig
	}
	return nil
}

func (x *TenantInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TenantInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// QuotaInfo 配额信息
type QuotaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotaId       int64                  `protobuf:"varint,1,opt,name=quota_id,json=quotaId,proto3" json:"quota_id,omitempty"`                                                 // 配额ID
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                               // 租户ID
	QuotaType     QuotaType              `protobuf:"varint,3,opt,name=quota_type,json=quotaType,proto3,enum=platform.tenant_service.v1.QuotaType" json:"quota_type,omitempty"` // 配额类型
	LimitType     LimitType              `protobuf:"varint,4,opt,name=limit_type,json=limitType,proto3,enum=platform.tenant_service.v1.LimitType" json:"limit_type,omitempty"` // 限制类型
	HardLimit     int32                  `protobuf:"varint,5,opt,name=hard_limit,json=hardLimit,proto3" json:"hard_limit,omitempty"`                                           // 硬限制
	SoftLimit     int32                  `protobuf:"varint,6,opt,name=soft_limit,json=softLimit,proto3" json:"soft_limit,omitempty"`                                           // 软限制
	UsedCount     int32                  `protobuf:"varint,7,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`                                           // 已使用数量
	ResetTime     string                 `protobuf:"bytes,8,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`                                            // 重置时间
	NextResetTime string                 `protobuf:"bytes,9,opt,name=next_reset_time,json=nextResetTime,proto3" json:"next_reset_time,omitempty"`                              // 下次重置时间
	EffectiveTime string                 `protobuf:"bytes,10,opt,name=effective_time,json=effectiveTime,proto3" json:"effective_time,omitempty"`                               // 生效时间
	ExpireTime    string                 `protobuf:"bytes,11,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                                        // 过期时间
	IsGlobal      bool                   `protobuf:"varint,12,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`                                             // 是否全局
	ProductCodes  []string               `protobuf:"bytes,13,rep,name=product_codes,json=productCodes,proto3" json:"product_codes,omitempty"`                                  // 产品代码列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaInfo) GetQuotaId() int64 {
	if x != nil {
		return x.QuotaId
	}
	return 0
}

func (x *QuotaInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QuotaInfo) GetQuotaType() QuotaType {
	if x != nil {
		return x.QuotaType
	}
	return QuotaType_QUOTA_TYPE_UNSPECIFIED
}

func (x *QuotaInfo) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_LIMIT_TYPE_UNSPECIFIED
}

func (x *QuotaInfo) GetHardLimit() int32 {
	if x != nil {
		return x.HardLimit
	}
	return 0
}

func (x *QuotaInfo) GetSoftLimit() int32 {
	if x != nil {
		return x.SoftLimit
	}
	return 0
}

func (x *QuotaInfo) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *QuotaInfo) GetResetTime() string {
	if x != nil {
		return x.ResetTime
	}
	return ""
}

func (x *QuotaInfo) GetNextResetTime() string {
	if x != nil {
		return x.NextResetTime
	}
	return ""
}

func (x *QuotaInfo) GetEffectiveTime() string {
	if x != nil {
		return x.EffectiveTime
	}
	return ""
}

func (x *QuotaInfo) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *QuotaInfo) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *QuotaInfo) GetProductCodes() []string {
	if x != nil {
		return x.ProductCodes
	}
	return nil
}

// Product 产品信息
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"` // 产品代码
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // 产品名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                    // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Product) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateTenantRequest 创建租户请求
type CreateTenantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantName     string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`                                                                              // 租户名称
	TenantType     TenantType             `protobuf:"varint,2,opt,name=tenant_type,json=tenantType,proto3,enum=platform.tenant_service.v1.TenantType" json:"tenant_type,omitempty"`                                  // 租户类型
	ParentTenantId string                 `protobuf:"bytes,3,opt,name=parent_tenant_id,json=parentTenantId,proto3" json:"parent_tenant_id,omitempty"`                                                                // 父租户ID
	QuotaConfig    map[string]string      `protobuf:"bytes,4,rep,name=quota_config,json=quotaConfig,proto3" json:"quota_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配额配置
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTenantRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *CreateTenantRequest) GetTenantType() TenantType {
	if x != nil {
		return x.TenantType
	}
	return TenantType_TENANT_TYPE_UNSPECIFIED
}

func (x *CreateTenantRequest) GetParentTenantId() string {
	if x != nil {
		return x.ParentTenantId
	}
	return ""
}

func (x *CreateTenantRequest) GetQuotaConfig() map[string]string {
	if x != nil {
		return x.QuotaConfig
	}
	return nil
}

// CreateTenantReply 创建租户响应
type CreateTenantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"` // 租户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantReply) Reset() {
	*x = CreateTenantReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantReply) ProtoMessage() {}

func (x *CreateTenantReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantReply.ProtoReflect.Descriptor instead.
func (*CreateTenantReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTenantReply) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// GetTenantRequest 获取租户请求
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetTenantReply 获取租户响应
type GetTenantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"` // 租户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantReply) Reset() {
	*x = GetTenantReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantReply) ProtoMessage() {}

func (x *GetTenantReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantReply.ProtoReflect.Descriptor instead.
func (*GetTenantReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *GetTenantReply) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// ListTenantsRequest 列出租户请求
type ListTenantsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantType     TenantType             `protobuf:"varint,1,opt,name=tenant_type,json=tenantType,proto3,enum=platform.tenant_service.v1.TenantType" json:"tenant_type,omitempty"` // 租户类型
	ParentTenantId string                 `protobuf:"bytes,2,opt,name=parent_tenant_id,json=parentTenantId,proto3" json:"parent_tenant_id,omitempty"`                               // 父租户ID
	Status         bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                                                      // 状态
	PageSize       int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                                                  // 页大小
	PageNum        int32                  `protobuf:"varint,5,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                                                     // 页码
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *ListTenantsRequest) GetTenantType() TenantType {
	if x != nil {
		return x.TenantType
	}
	return TenantType_TENANT_TYPE_UNSPECIFIED
}

func (x *ListTenantsRequest) GetParentTenantId() string {
	if x != nil {
		return x.ParentTenantId
	}
	return ""
}

func (x *ListTenantsRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ListTenantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

// ListTenantsReply 列出租户响应
type ListTenantsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"` // 租户列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsReply) Reset() {
	*x = ListTenantsReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsReply) ProtoMessage() {}

func (x *ListTenantsReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsReply.ProtoReflect.Descriptor instead.
func (*ListTenantsReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *ListTenantsReply) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateTenantRequest 更新租户请求
type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                                                    // 租户ID
	TenantName    string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`                                                                              // 租户名称
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                                                                                       // 状态
	QuotaConfig   map[string]string      `protobuf:"bytes,4,rep,name=quota_config,json=quotaConfig,proto3" json:"quota_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配额配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *UpdateTenantRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateTenantRequest) GetQuotaConfig() map[string]string {
	if x != nil {
		return x.QuotaConfig
	}
	return nil
}

// UpdateTenantReply 更新租户响应
type UpdateTenantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"` // 租户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantReply) Reset() {
	*x = UpdateTenantReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantReply) ProtoMessage() {}

func (x *UpdateTenantReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantReply.ProtoReflect.Descriptor instead.
func (*UpdateTenantReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTenantReply) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// DeleteTenantRequest 删除租户请求
type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// DeleteTenantReply 删除租户响应
type DeleteTenantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantReply) Reset() {
	*x = DeleteTenantReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantReply) ProtoMessage() {}

func (x *DeleteTenantReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantReply.ProtoReflect.Descriptor instead.
func (*DeleteTenantReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTenantReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CheckQuotaRequest 检查配额请求
type CheckQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                               // 租户ID
	QuotaType     QuotaType              `protobuf:"varint,2,opt,name=quota_type,json=quotaType,proto3,enum=platform.tenant_service.v1.QuotaType" json:"quota_type,omitempty"` // 配额类型
	LimitType     LimitType              `protobuf:"varint,3,opt,name=limit_type,json=limitType,proto3,enum=platform.tenant_service.v1.LimitType" json:"limit_type,omitempty"` // 限制类型
	ProductCode   string                 `protobuf:"bytes,4,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`                                      // 产品代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaRequest) Reset() {
	*x = CheckQuotaRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaRequest) ProtoMessage() {}

func (x *CheckQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckQuotaRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *CheckQuotaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckQuotaRequest) GetQuotaType() QuotaType {
	if x != nil {
		return x.QuotaType
	}
	return QuotaType_QUOTA_TYPE_UNSPECIFIED
}

func (x *CheckQuotaRequest) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_LIMIT_TYPE_UNSPECIFIED
}

func (x *CheckQuotaRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

// CheckQuotaReply 检查配额响应
type CheckQuotaReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Quota          *QuotaInfo             `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`                                          // 配额信息
	HasQuota       bool                   `protobuf:"varint,2,opt,name=has_quota,json=hasQuota,proto3" json:"has_quota,omitempty"`                   // 是否有配额
	AvailableQuota int32                  `protobuf:"varint,3,opt,name=available_quota,json=availableQuota,proto3" json:"available_quota,omitempty"` // 可用配额
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckQuotaReply) Reset() {
	*x = CheckQuotaReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaReply) ProtoMessage() {}

func (x *CheckQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaReply.ProtoReflect.Descriptor instead.
func (*CheckQuotaReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *CheckQuotaReply) GetQuota() *QuotaInfo {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *CheckQuotaReply) GetHasQuota() bool {
	if x != nil {
		return x.HasQuota
	}
	return false
}

func (x *CheckQuotaReply) GetAvailableQuota() int32 {
	if x != nil {
		return x.AvailableQuota
	}
	return 0
}

// ConsumeQuotaRequest 消费配额请求
type ConsumeQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                               // 租户ID
	QuotaType     QuotaType              `protobuf:"varint,2,opt,name=quota_type,json=quotaType,proto3,enum=platform.tenant_service.v1.QuotaType" json:"quota_type,omitempty"` // 配额类型
	LimitType     LimitType              `protobuf:"varint,3,opt,name=limit_type,json=limitType,proto3,enum=platform.tenant_service.v1.LimitType" json:"limit_type,omitempty"` // 限制类型
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                                  // 数量
	ProductCode   string                 `protobuf:"bytes,5,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`                                      // 产品代码
	BizId         string                 `protobuf:"bytes,6,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                                                        // 业务ID
	BizType       string                 `protobuf:"bytes,7,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`                                                  // 业务类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeQuotaRequest) Reset() {
	*x = ConsumeQuotaRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeQuotaRequest) ProtoMessage() {}

func (x *ConsumeQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeQuotaRequest.ProtoReflect.Descriptor instead.
func (*ConsumeQuotaRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *ConsumeQuotaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConsumeQuotaRequest) GetQuotaType() QuotaType {
	if x != nil {
		return x.QuotaType
	}
	return QuotaType_QUOTA_TYPE_UNSPECIFIED
}

func (x *ConsumeQuotaRequest) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_LIMIT_TYPE_UNSPECIFIED
}

func (x *ConsumeQuotaRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsumeQuotaRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *ConsumeQuotaRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConsumeQuotaRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

// ConsumeQuotaReply 消费配额响应
type ConsumeQuotaReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // 是否成功
	RemainingQuota int32                  `protobuf:"varint,2,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"` // 剩余配额
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                      // 消息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumeQuotaReply) Reset() {
	*x = ConsumeQuotaReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeQuotaReply) ProtoMessage() {}

func (x *ConsumeQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeQuotaReply.ProtoReflect.Descriptor instead.
func (*ConsumeQuotaReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *ConsumeQuotaReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeQuotaReply) GetRemainingQuota() int32 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *ConsumeQuotaReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReleaseQuotaRequest 释放配额请求
type ReleaseQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                               // 租户ID
	QuotaType     QuotaType              `protobuf:"varint,2,opt,name=quota_type,json=quotaType,proto3,enum=platform.tenant_service.v1.QuotaType" json:"quota_type,omitempty"` // 配额类型
	LimitType     LimitType              `protobuf:"varint,3,opt,name=limit_type,json=limitType,proto3,enum=platform.tenant_service.v1.LimitType" json:"limit_type,omitempty"` // 限制类型
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                                  // 数量
	ProductCode   string                 `protobuf:"bytes,5,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`                                      // 产品代码
	BizId         string                 `protobuf:"bytes,6,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                                                        // 业务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseQuotaRequest) Reset() {
	*x = ReleaseQuotaRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseQuotaRequest) ProtoMessage() {}

func (x *ReleaseQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseQuotaRequest.ProtoReflect.Descriptor instead.
func (*ReleaseQuotaRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseQuotaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReleaseQuotaRequest) GetQuotaType() QuotaType {
	if x != nil {
		return x.QuotaType
	}
	return QuotaType_QUOTA_TYPE_UNSPECIFIED
}

func (x *ReleaseQuotaRequest) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_LIMIT_TYPE_UNSPECIFIED
}

func (x *ReleaseQuotaRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReleaseQuotaRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *ReleaseQuotaRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

// ReleaseQuotaReply 释放配额响应
type ReleaseQuotaReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // 是否成功
	RemainingQuota int32                  `protobuf:"varint,2,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"` // 剩余配额
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                      // 消息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseQuotaReply) Reset() {
	*x = ReleaseQuotaReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseQuotaReply) ProtoMessage() {}

func (x *ReleaseQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseQuotaReply.ProtoReflect.Descriptor instead.
func (*ReleaseQuotaReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *ReleaseQuotaReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseQuotaReply) GetRemainingQuota() int32 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *ReleaseQuotaReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListProductsRequest 列出产品线请求
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{19}
}

func (x *ListProductsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListProductsReply 列出产品线响应
type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"` // 产品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_tenant_service_v1_tenant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_platform_tenant_service_v1_tenant_proto_rawDescGZIP(), []int{20}
}

func (x *ListProductsReply) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_platform_tenant_service_v1_tenant_proto protoreflect.FileDescriptor

const file_platform_tenant_service_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"'platform/tenant_service/v1/tenant.proto\x12\x1aplatform.tenant_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x10base/error.proto\x1a\x15base/pagination.proto\"\xaf\x03\n" +
	"\n" +
	"TenantInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\x12G\n" +
	"\vtenant_type\x18\x03 \x01(\x0e2&.platform.tenant_service.v1.TenantTypeR\n" +
	"tenantType\x12(\n" +
	"\x10parent_tenant_id\x18\x04 \x01(\tR\x0eparentTenantId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12Z\n" +
	"\fquota_config\x18\x06 \x03(\v27.platform.tenant_service.v1.TenantInfo.QuotaConfigEntryR\vquotaConfig\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x1a>\n" +
	"\x10QuotaConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x03\n" +
	"\tQuotaInfo\x12\x19\n" +
	"\bquota_id\x18\x01 \x01(\x03R\aquotaId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12D\n" +
	"\n" +
	"quota_type\x18\x03 \x01(\x0e2%.platform.tenant_service.v1.QuotaTypeR\tquotaType\x12D\n" +
	"\n" +
	"limit_type\x18\x04 \x01(\x0e2%.platform.tenant_service.v1.LimitTypeR\tlimitType\x12\x1d\n" +
	"\n" +
	"hard_limit\x18\x05 \x01(\x05R\thardLimit\x12\x1d\n" +
	"\n" +
	"soft_limit\x18\x06 \x01(\x05R\tsoftLimit\x12\x1d\n" +
	"\n" +
	"used_count\x18\a \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"reset_time\x18\b \x01(\tR\tresetTime\x12&\n" +
	"\x0fnext_reset_time\x18\t \x01(\tR\rnextResetTime\x12%\n" +
	"\x0eeffective_time\x18\n" +
	" \x01(\tR\reffectiveTime\x12\x1f\n" +
	"\vexpire_time\x18\v \x01(\tR\n" +
	"expireTime\x12\x1b\n" +
	"\tis_global\x18\f \x01(\bR\bisGlobal\x12#\n" +
	"\rproduct_codes\x18\r \x03(\tR\fproductCodes\"q\n" +
	"\aProduct\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xe3\x02\n" +
	"\x13CreateTenantRequest\x12*\n" +
	"\vtenant_name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\n" +
	"tenantName\x12Q\n" +
	"\vtenant_type\x18\x02 \x01(\x0e2&.platform.tenant_service.v1.TenantTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"tenantType\x12(\n" +
	"\x10parent_tenant_id\x18\x03 \x01(\tR\x0eparentTenantId\x12c\n" +
	"\fquota_config\x18\x04 \x03(\v2@.platform.tenant_service.v1.CreateTenantRequest.QuotaConfigEntryR\vquotaConfig\x1a>\n" +
	"\x10QuotaConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x11CreateTenantReply\x12>\n" +
	"\x06tenant\x18\x01 \x01(\v2&.platform.tenant_service.v1.TenantInfoR\x06tenant\"8\n" +
	"\x10GetTenantRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\"P\n" +
	"\x0eGetTenantReply\x12>\n" +
	"\x06tenant\x18\x01 \x01(\v2&.platform.tenant_service.v1.TenantInfoR\x06tenant\"\xd7\x01\n" +
	"\x12ListTenantsRequest\x12G\n" +
	"\vtenant_type\x18\x01 \x01(\x0e2&.platform.tenant_service.v1.TenantTypeR\n" +
	"tenantType\x12(\n" +
	"\x10parent_tenant_id\x18\x02 \x01(\tR\x0eparentTenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x05 \x01(\x05R\apageNum\"j\n" +
	"\x10ListTenantsReply\x12@\n" +
	"\atenants\x18\x01 \x03(\v2&.platform.tenant_service.v1.TenantInfoR\atenants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa4\x02\n" +
	"\x13UpdateTenantRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\x12*\n" +
	"\vtenant_name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\n" +
	"tenantName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12c\n" +
	"\fquota_config\x18\x04 \x03(\v2@.platform.tenant_service.v1.UpdateTenantRequest.QuotaConfigEntryR\vquotaConfig\x1a>\n" +
	"\x10QuotaConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x11UpdateTenantReply\x12>\n" +
	"\x06tenant\x18\x01 \x01(\v2&.platform.tenant_service.v1.TenantInfoR\x06tenant\";\n" +
	"\x13DeleteTenantRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\"-\n" +
	"\x11DeleteTenantReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xfc\x01\n" +
	"\x11CheckQuotaRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\x12N\n" +
	"\n" +
	"quota_type\x18\x02 \x01(\x0e2%.platform.tenant_service.v1.QuotaTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tquotaType\x12N\n" +
	"\n" +
	"limit_type\x18\x03 \x01(\x0e2%.platform.tenant_service.v1.LimitTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tlimitType\x12!\n" +
	"\fproduct_code\x18\x04 \x01(\tR\vproductCode\"\x94\x01\n" +
	"\x0fCheckQuotaReply\x12;\n" +
	"\x05quota\x18\x01 \x01(\v2%.platform.tenant_service.v1.QuotaInfoR\x05quota\x12\x1b\n" +
	"\thas_quota\x18\x02 \x01(\bR\bhasQuota\x12'\n" +
	"\x0favailable_quota\x18\x03 \x01(\x05R\x0eavailableQuota\"\xd1\x02\n" +
	"\x13ConsumeQuotaRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\x12N\n" +
	"\n" +
	"quota_type\x18\x02 \x01(\x0e2%.platform.tenant_service.v1.QuotaTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tquotaType\x12N\n" +
	"\n" +
	"limit_type\x18\x03 \x01(\x0e2%.platform.tenant_service.v1.LimitTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tlimitType\x12\x1f\n" +
	"\x06amount\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06amount\x12!\n" +
	"\fproduct_code\x18\x05 \x01(\tR\vproductCode\x12\x15\n" +
	"\x06biz_id\x18\x06 \x01(\tR\x05bizId\x12\x19\n" +
	"\bbiz_type\x18\a \x01(\tR\abizType\"p\n" +
	"\x11ConsumeQuotaReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fremaining_quota\x18\x02 \x01(\x05R\x0eremainingQuota\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb6\x02\n" +
	"\x13ReleaseQuotaRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\btenantId\x12N\n" +
	"\n" +
	"quota_type\x18\x02 \x01(\x0e2%.platform.tenant_service.v1.QuotaTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tquotaType\x12N\n" +
	"\n" +
	"limit_type\x18\x03 \x01(\x0e2%.platform.tenant_service.v1.LimitTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\tlimitType\x12\x1f\n" +
	"\x06amount\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06amount\x12!\n" +
	"\fproduct_code\x18\x05 \x01(\tR\vproductCode\x12\x15\n" +
	"\x06biz_id\x18\x06 \x01(\tR\x05bizId\"p\n" +
	"\x11ReleaseQuotaReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fremaining_quota\x18\x02 \x01(\x05R\x0eremainingQuota\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"T\n" +
	"\x11ListProductsReply\x12?\n" +
	"\bproducts\x18\x01 \x03(\v2#.platform.tenant_service.v1.ProductR\bproducts*x\n" +
	"\n" +
	"TenantType\x12\x1b\n" +
	"\x17TENANT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TENANT_TYPE_PLATFORM\x10\x01\x12\x17\n" +
	"\x13TENANT_TYPE_CHANNEL\x10\x02\x12\x1a\n" +
	"\x16TENANT_TYPE_ENTERPRISE\x10\x03*z\n" +
	"\tQuotaType\x12\x1a\n" +
	"\x16QUOTA_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dQUOTA_TYPE_MARKETING_CAMPAIGN\x10\x01\x12\x1a\n" +
	"\x16QUOTA_TYPE_REDEEM_CODE\x10\x02\x12\x12\n" +
	"\x0eQUOTA_TYPE_SMS\x10\x03*\x86\x01\n" +
	"\tLimitType\x12\x1a\n" +
	"\x16LIMIT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LIMIT_TYPE_DAILY\x10\x01\x12\x16\n" +
	"\x12LIMIT_TYPE_MONTHLY\x10\x02\x12\x14\n" +
	"\x10LIMIT_TYPE_TOTAL\x10\x03\x12\x19\n" +
	"\x15LIMIT_TYPE_CONCURRENT\x10\x04*\x82\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OPERATION_TYPE_CONSUME\x10\x01\x12\x1a\n" +
	"\x16OPERATION_TYPE_RELEASE\x10\x02\x12\x19\n" +
	"\x15OPERATION_TYPE_ADJUST\x10\x032\xac\n" +
	"\n" +
	"\x06Tenant\x12\x86\x01\n" +
	"\fCreateTenant\x12/.platform.tenant_service.v1.CreateTenantRequest\x1a-.platform.tenant_service.v1.CreateTenantReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tenants\x12\x86\x01\n" +
	"\tGetTenant\x12,.platform.tenant_service.v1.GetTenantRequest\x1a*.platform.tenant_service.v1.GetTenantReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/tenants/{tenant_id}\x12\x80\x01\n" +
	"\vListTenants\x12..platform.tenant_service.v1.ListTenantsRequest\x1a,.platform.tenant_service.v1.ListTenantsReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/tenants\x12\x92\x01\n" +
	"\fUpdateTenant\x12/.platform.tenant_service.v1.UpdateTenantRequest\x1a-.platform.tenant_service.v1.UpdateTenantReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/tenants/{tenant_id}\x12\x8f\x01\n" +
	"\fDeleteTenant\x12/.platform.tenant_service.v1.DeleteTenantRequest\x1a-.platform.tenant_service.v1.DeleteTenantReply\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/tenants/{tenant_id}\x12\x98\x01\n" +
	"\n" +
	"CheckQuota\x12-.platform.tenant_service.v1.CheckQuotaRequest\x1a+.platform.tenant_service.v1.CheckQuotaReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/tenants/{tenant_id}/quota/check\x12\xa0\x01\n" +
	"\fConsumeQuota\x12/.platform.tenant_service.v1.ConsumeQuotaRequest\x1a-.platform.tenant_service.v1.ConsumeQuotaReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/tenants/{tenant_id}/quota/consume\x12\xa0\x01\n" +
	"\fReleaseQuota\x12/.platform.tenant_service.v1.ReleaseQuotaRequest\x1a-.platform.tenant_service.v1.ReleaseQuotaReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/tenants/{tenant_id}/quota/release\x12\x84\x01\n" +
	"\fListProducts\x12/.platform.tenant_service.v1.ListProductsRequest\x1a-.platform.tenant_service.v1.ListProductsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/productsBSZQtenant-service/api/tenant_service/v1;v1b\x06proto3"

var (
	file_platform_tenant_service_v1_tenant_proto_rawDescOnce sync.Once
	file_platform_tenant_service_v1_tenant_proto_rawDescData []byte
)

func file_platform_tenant_service_v1_tenant_proto_rawDescGZIP() []byte {
	file_platform_tenant_service_v1_tenant_proto_rawDescOnce.Do(func() {
		file_platform_tenant_service_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_tenant_service_v1_tenant_proto_rawDesc), len(file_platform_tenant_service_v1_tenant_proto_rawDesc)))
	})
	return file_platform_tenant_service_v1_tenant_proto_rawDescData
}

var file_platform_tenant_service_v1_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_platform_tenant_service_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_platform_tenant_service_v1_tenant_proto_goTypes = []any{
	(TenantType)(0),             // 0: platform.tenant_service.v1.TenantType
	(QuotaType)(0),              // 1: platform.tenant_service.v1.QuotaType
	(LimitType)(0),              // 2: platform.tenant_service.v1.LimitType
	(OperationType)(0),          // 3: platform.tenant_service.v1.OperationType
	(*TenantInfo)(nil),          // 4: platform.tenant_service.v1.TenantInfo
	(*QuotaInfo)(nil),           // 5: platform.tenant_service.v1.QuotaInfo
	(*Product)(nil),             // 6: platform.tenant_service.v1.Product
	(*CreateTenantRequest)(nil), // 7: platform.tenant_service.v1.CreateTenantRequest
	(*CreateTenantReply)(nil),   // 8: platform.tenant_service.v1.CreateTenantReply
	(*GetTenantRequest)(nil),    // 9: platform.tenant_service.v1.GetTenantRequest
	(*GetTenantReply)(nil),      // 10: platform.tenant_service.v1.GetTenantReply
	(*ListTenantsRequest)(nil),  // 11: platform.tenant_service.v1.ListTenantsRequest
	(*ListTenantsReply)(nil),    // 12: platform.tenant_service.v1.ListTenantsReply
	(*UpdateTenantRequest)(nil), // 13: platform.tenant_service.v1.UpdateTenantRequest
	(*UpdateTenantReply)(nil),   // 14: platform.tenant_service.v1.UpdateTenantReply
	(*DeleteTenantRequest)(nil), // 15: platform.tenant_service.v1.DeleteTenantRequest
	(*DeleteTenantReply)(nil),   // 16: platform.tenant_service.v1.DeleteTenantReply
	(*CheckQuotaRequest)(nil),   // 17: platform.tenant_service.v1.CheckQuotaRequest
	(*CheckQuotaReply)(nil),     // 18: platform.tenant_service.v1.CheckQuotaReply
	(*ConsumeQuotaRequest)(nil), // 19: platform.tenant_service.v1.ConsumeQuotaRequest
	(*ConsumeQuotaReply)(nil),   // 20: platform.tenant_service.v1.ConsumeQuotaReply
	(*ReleaseQuotaRequest)(nil), // 21: platform.tenant_service.v1.ReleaseQuotaRequest
	(*ReleaseQuotaReply)(nil),   // 22: platform.tenant_service.v1.ReleaseQuotaReply
	(*ListProductsRequest)(nil), // 23: platform.tenant_service.v1.ListProductsRequest
	(*ListProductsReply)(nil),   // 24: platform.tenant_service.v1.ListProductsReply
	nil,                         // 25: platform.tenant_service.v1.TenantInfo.QuotaConfigEntry
	nil,                         // 26: platform.tenant_service.v1.CreateTenantRequest.QuotaConfigEntry
	nil,                         // 27: platform.tenant_service.v1.UpdateTenantRequest.QuotaConfigEntry
}
var file_platform_tenant_service_v1_tenant_proto_depIdxs = []int32{
	0,  // 0: platform.tenant_service.v1.TenantInfo.tenant_type:type_name -> platform.tenant_service.v1.TenantType
	25, // 1: platform.tenant_service.v1.TenantInfo.quota_config:type_name -> platform.tenant_service.v1.TenantInfo.QuotaConfigEntry
	1,  // 2: platform.tenant_service.v1.QuotaInfo.quota_type:type_name -> platform.tenant_service.v1.QuotaType
	2,  // 3: platform.tenant_service.v1.QuotaInfo.limit_type:type_name -> platform.tenant_service.v1.LimitType
	0,  // 4: platform.tenant_service.v1.CreateTenantRequest.tenant_type:type_name -> platform.tenant_service.v1.TenantType
	26, // 5: platform.tenant_service.v1.CreateTenantRequest.quota_config:type_name -> platform.tenant_service.v1.CreateTenantRequest.QuotaConfigEntry
	4,  // 6: platform.tenant_service.v1.CreateTenantReply.tenant:type_name -> platform.tenant_service.v1.TenantInfo
	4,  // 7: platform.tenant_service.v1.GetTenantReply.tenant:type_name -> platform.tenant_service.v1.TenantInfo
	0,  // 8: platform.tenant_service.v1.ListTenantsRequest.tenant_type:type_name -> platform.tenant_service.v1.TenantType
	4,  // 9: platform.tenant_service.v1.ListTenantsReply.tenants:type_name -> platform.tenant_service.v1.TenantInfo
	27, // 10: platform.tenant_service.v1.UpdateTenantRequest.quota_config:type_name -> platform.tenant_service.v1.UpdateTenantRequest.QuotaConfigEntry
	4,  // 11: platform.tenant_service.v1.UpdateTenantReply.tenant:type_name -> platform.tenant_service.v1.TenantInfo
	1,  // 12: platform.tenant_service.v1.CheckQuotaRequest.quota_type:type_name -> platform.tenant_service.v1.QuotaType
	2,  // 13: platform.tenant_service.v1.CheckQuotaRequest.limit_type:type_name -> platform.tenant_service.v1.LimitType
	5,  // 14: platform.tenant_service.v1.CheckQuotaReply.quota:type_name -> platform.tenant_service.v1.QuotaInfo
	1,  // 15: platform.tenant_service.v1.ConsumeQuotaRequest.quota_type:type_name -> platform.tenant_service.v1.QuotaType
	2,  // 16: platform.tenant_service.v1.ConsumeQuotaRequest.limit_type:type_name -> platform.tenant_service.v1.LimitType
	1,  // 17: platform.tenant_service.v1.ReleaseQuotaRequest.quota_type:type_name -> platform.tenant_service.v1.QuotaType
	2,  // 18: platform.tenant_service.v1.ReleaseQuotaRequest.limit_type:type_name -> platform.tenant_service.v1.LimitType
	6,  // 19: platform.tenant_service.v1.ListProductsReply.products:type_name -> platform.tenant_service.v1.Product
	7,  // 20: platform.tenant_service.v1.Tenant.CreateTenant:input_type -> platform.tenant_service.v1.CreateTenantRequest
	9,  // 21: platform.tenant_service.v1.Tenant.GetTenant:input_type -> platform.tenant_service.v1.GetTenantRequest
	11, // 22: platform.tenant_service.v1.Tenant.ListTenants:input_type -> platform.tenant_service.v1.ListTenantsRequest
	13, // 23: platform.tenant_service.v1.Tenant.UpdateTenant:input_type -> platform.tenant_service.v1.UpdateTenantRequest
	15, // 24: platform.tenant_service.v1.Tenant.DeleteTenant:input_type -> platform.tenant_service.v1.DeleteTenantRequest
	17, // 25: platform.tenant_service.v1.Tenant.CheckQuota:input_type -> platform.tenant_service.v1.CheckQuotaRequest
	19, // 26: platform.tenant_service.v1.Tenant.ConsumeQuota:input_type -> platform.tenant_service.v1.ConsumeQuotaRequest
	21, // 27: platform.tenant_service.v1.Tenant.ReleaseQuota:input_type -> platform.tenant_service.v1.ReleaseQuotaRequest
	23, // 28: platform.tenant_service.v1.Tenant.ListProducts:input_type -> platform.tenant_service.v1.ListProductsRequest
	8,  // 29: platform.tenant_service.v1.Tenant.CreateTenant:output_type -> platform.tenant_service.v1.CreateTenantReply
	10, // 30: platform.tenant_service.v1.Tenant.GetTenant:output_type -> platform.tenant_service.v1.GetTenantReply
	12, // 31: platform.tenant_service.v1.Tenant.ListTenants:output_type -> platform.tenant_service.v1.ListTenantsReply
	14, // 32: platform.tenant_service.v1.Tenant.UpdateTenant:output_type -> platform.tenant_service.v1.UpdateTenantReply
	16, // 33: platform.tenant_service.v1.Tenant.DeleteTenant:output_type -> platform.tenant_service.v1.DeleteTenantReply
	18, // 34: platform.tenant_service.v1.Tenant.CheckQuota:output_type -> platform.tenant_service.v1.CheckQuotaReply
	20, // 35: platform.tenant_service.v1.Tenant.ConsumeQuota:output_type -> platform.tenant_service.v1.ConsumeQuotaReply
	22, // 36: platform.tenant_service.v1.Tenant.ReleaseQuota:output_type -> platform.tenant_service.v1.ReleaseQuotaReply
	24, // 37: platform.tenant_service.v1.Tenant.ListProducts:output_type -> platform.tenant_service.v1.ListProductsReply
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_platform_tenant_service_v1_tenant_proto_init() }
func file_platform_tenant_service_v1_tenant_proto_init() {
	if File_platform_tenant_service_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_tenant_service_v1_tenant_proto_rawDesc), len(file_platform_tenant_service_v1_tenant_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_tenant_service_v1_tenant_proto_goTypes,
		DependencyIndexes: file_platform_tenant_service_v1_tenant_proto_depIdxs,
		EnumInfos:         file_platform_tenant_service_v1_tenant_proto_enumTypes,
		MessageInfos:      file_platform_tenant_service_v1_tenant_proto_msgTypes,
	}.Build()
	File_platform_tenant_service_v1_tenant_proto = out.File
	file_platform_tenant_service_v1_tenant_proto_goTypes = nil
	file_platform_tenant_service_v1_tenant_proto_depIdxs = nil
}
