// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: platform/tenant_service/v1/tenant.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TenantInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantInfoMultiError, or
// nil if none found.
func (m *TenantInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for TenantName

	// no validation rules for TenantType

	// no validation rules for ParentTenantId

	// no validation rules for Status

	// no validation rules for QuotaConfig

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return TenantInfoMultiError(errors)
	}

	return nil
}

// TenantInfoMultiError is an error wrapping multiple validation errors
// returned by TenantInfo.ValidateAll() if the designated constraints aren't met.
type TenantInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantInfoMultiError) AllErrors() []error { return m }

// TenantInfoValidationError is the validation error returned by
// TenantInfo.Validate if the designated constraints aren't met.
type TenantInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantInfoValidationError) ErrorName() string { return "TenantInfoValidationError" }

// Error satisfies the builtin error interface
func (e TenantInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantInfoValidationError{}

// Validate checks the field values on QuotaInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuotaInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuotaInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuotaInfoMultiError, or nil
// if none found.
func (m *QuotaInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *QuotaInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for QuotaId

	// no validation rules for TenantId

	// no validation rules for QuotaType

	// no validation rules for LimitType

	// no validation rules for HardLimit

	// no validation rules for SoftLimit

	// no validation rules for UsedCount

	// no validation rules for ResetTime

	// no validation rules for NextResetTime

	// no validation rules for EffectiveTime

	// no validation rules for ExpireTime

	// no validation rules for IsGlobal

	if len(errors) > 0 {
		return QuotaInfoMultiError(errors)
	}

	return nil
}

// QuotaInfoMultiError is an error wrapping multiple validation errors returned
// by QuotaInfo.ValidateAll() if the designated constraints aren't met.
type QuotaInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuotaInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuotaInfoMultiError) AllErrors() []error { return m }

// QuotaInfoValidationError is the validation error returned by
// QuotaInfo.Validate if the designated constraints aren't met.
type QuotaInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuotaInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuotaInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuotaInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuotaInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuotaInfoValidationError) ErrorName() string { return "QuotaInfoValidationError" }

// Error satisfies the builtin error interface
func (e QuotaInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuotaInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuotaInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuotaInfoValidationError{}

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Product) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProductMultiError, or nil if none found.
func (m *Product) ValidateAll() error {
	return m.validate(true)
}

func (m *Product) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductCode

	// no validation rules for ProductName

	// no validation rules for Description

	if len(errors) > 0 {
		return ProductMultiError(errors)
	}

	return nil
}

// ProductMultiError is an error wrapping multiple validation errors returned
// by Product.ValidateAll() if the designated constraints aren't met.
type ProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductMultiError) AllErrors() []error { return m }

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}

// Validate checks the field values on CreateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTenantRequestMultiError, or nil if none found.
func (m *CreateTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTenantName()); l < 1 || l > 64 {
		err := CreateTenantRequestValidationError{
			field:  "TenantName",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := TenantType_name[int32(m.GetTenantType())]; !ok {
		err := CreateTenantRequestValidationError{
			field:  "TenantType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ParentTenantId

	// no validation rules for QuotaConfig

	if len(errors) > 0 {
		return CreateTenantRequestMultiError(errors)
	}

	return nil
}

// CreateTenantRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTenantRequestMultiError) AllErrors() []error { return m }

// CreateTenantRequestValidationError is the validation error returned by
// CreateTenantRequest.Validate if the designated constraints aren't met.
type CreateTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTenantRequestValidationError) ErrorName() string {
	return "CreateTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTenantRequestValidationError{}

// Validate checks the field values on CreateTenantReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateTenantReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTenantReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTenantReplyMultiError, or nil if none found.
func (m *CreateTenantReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTenantReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTenant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTenantReplyValidationError{
				field:  "Tenant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateTenantReplyMultiError(errors)
	}

	return nil
}

// CreateTenantReplyMultiError is an error wrapping multiple validation errors
// returned by CreateTenantReply.ValidateAll() if the designated constraints
// aren't met.
type CreateTenantReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTenantReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTenantReplyMultiError) AllErrors() []error { return m }

// CreateTenantReplyValidationError is the validation error returned by
// CreateTenantReply.Validate if the designated constraints aren't met.
type CreateTenantReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTenantReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTenantReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTenantReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTenantReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTenantReplyValidationError) ErrorName() string {
	return "CreateTenantReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTenantReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTenantReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTenantReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTenantReplyValidationError{}

// Validate checks the field values on GetTenantRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTenantRequestMultiError, or nil if none found.
func (m *GetTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := GetTenantRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTenantRequestMultiError(errors)
	}

	return nil
}

// GetTenantRequestMultiError is an error wrapping multiple validation errors
// returned by GetTenantRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTenantRequestMultiError) AllErrors() []error { return m }

// GetTenantRequestValidationError is the validation error returned by
// GetTenantRequest.Validate if the designated constraints aren't met.
type GetTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTenantRequestValidationError) ErrorName() string { return "GetTenantRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTenantRequestValidationError{}

// Validate checks the field values on GetTenantReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTenantReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTenantReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetTenantReplyMultiError,
// or nil if none found.
func (m *GetTenantReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTenantReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTenant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTenantReplyValidationError{
				field:  "Tenant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTenantReplyMultiError(errors)
	}

	return nil
}

// GetTenantReplyMultiError is an error wrapping multiple validation errors
// returned by GetTenantReply.ValidateAll() if the designated constraints
// aren't met.
type GetTenantReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTenantReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTenantReplyMultiError) AllErrors() []error { return m }

// GetTenantReplyValidationError is the validation error returned by
// GetTenantReply.Validate if the designated constraints aren't met.
type GetTenantReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTenantReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTenantReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTenantReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTenantReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTenantReplyValidationError) ErrorName() string { return "GetTenantReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetTenantReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTenantReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTenantReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTenantReplyValidationError{}

// Validate checks the field values on ListTenantsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTenantsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantsRequestMultiError, or nil if none found.
func (m *ListTenantsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantType

	// no validation rules for ParentTenantId

	// no validation rules for Status

	// no validation rules for PageSize

	// no validation rules for PageNum

	if len(errors) > 0 {
		return ListTenantsRequestMultiError(errors)
	}

	return nil
}

// ListTenantsRequestMultiError is an error wrapping multiple validation errors
// returned by ListTenantsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListTenantsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsRequestMultiError) AllErrors() []error { return m }

// ListTenantsRequestValidationError is the validation error returned by
// ListTenantsRequest.Validate if the designated constraints aren't met.
type ListTenantsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsRequestValidationError) ErrorName() string {
	return "ListTenantsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTenantsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsRequestValidationError{}

// Validate checks the field values on ListTenantsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTenantsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantsReplyMultiError, or nil if none found.
func (m *ListTenantsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTenants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTenantsReplyValidationError{
						field:  fmt.Sprintf("Tenants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTenantsReplyValidationError{
						field:  fmt.Sprintf("Tenants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTenantsReplyValidationError{
					field:  fmt.Sprintf("Tenants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListTenantsReplyMultiError(errors)
	}

	return nil
}

// ListTenantsReplyMultiError is an error wrapping multiple validation errors
// returned by ListTenantsReply.ValidateAll() if the designated constraints
// aren't met.
type ListTenantsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsReplyMultiError) AllErrors() []error { return m }

// ListTenantsReplyValidationError is the validation error returned by
// ListTenantsReply.Validate if the designated constraints aren't met.
type ListTenantsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsReplyValidationError) ErrorName() string { return "ListTenantsReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListTenantsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsReplyValidationError{}

// Validate checks the field values on UpdateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTenantRequestMultiError, or nil if none found.
func (m *UpdateTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := UpdateTenantRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTenantName()); l < 1 || l > 64 {
		err := UpdateTenantRequestValidationError{
			field:  "TenantName",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	// no validation rules for QuotaConfig

	if len(errors) > 0 {
		return UpdateTenantRequestMultiError(errors)
	}

	return nil
}

// UpdateTenantRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTenantRequestMultiError) AllErrors() []error { return m }

// UpdateTenantRequestValidationError is the validation error returned by
// UpdateTenantRequest.Validate if the designated constraints aren't met.
type UpdateTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTenantRequestValidationError) ErrorName() string {
	return "UpdateTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTenantRequestValidationError{}

// Validate checks the field values on UpdateTenantReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateTenantReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTenantReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTenantReplyMultiError, or nil if none found.
func (m *UpdateTenantReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTenantReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTenant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTenantReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTenantReplyValidationError{
				field:  "Tenant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateTenantReplyMultiError(errors)
	}

	return nil
}

// UpdateTenantReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateTenantReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateTenantReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTenantReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTenantReplyMultiError) AllErrors() []error { return m }

// UpdateTenantReplyValidationError is the validation error returned by
// UpdateTenantReply.Validate if the designated constraints aren't met.
type UpdateTenantReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTenantReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTenantReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTenantReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTenantReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTenantReplyValidationError) ErrorName() string {
	return "UpdateTenantReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTenantReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTenantReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTenantReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTenantReplyValidationError{}

// Validate checks the field values on DeleteTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTenantRequestMultiError, or nil if none found.
func (m *DeleteTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := DeleteTenantRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteTenantRequestMultiError(errors)
	}

	return nil
}

// DeleteTenantRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTenantRequestMultiError) AllErrors() []error { return m }

// DeleteTenantRequestValidationError is the validation error returned by
// DeleteTenantRequest.Validate if the designated constraints aren't met.
type DeleteTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTenantRequestValidationError) ErrorName() string {
	return "DeleteTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTenantRequestValidationError{}

// Validate checks the field values on DeleteTenantReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteTenantReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTenantReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTenantReplyMultiError, or nil if none found.
func (m *DeleteTenantReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTenantReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteTenantReplyMultiError(errors)
	}

	return nil
}

// DeleteTenantReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteTenantReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteTenantReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTenantReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTenantReplyMultiError) AllErrors() []error { return m }

// DeleteTenantReplyValidationError is the validation error returned by
// DeleteTenantReply.Validate if the designated constraints aren't met.
type DeleteTenantReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTenantReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTenantReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTenantReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTenantReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTenantReplyValidationError) ErrorName() string {
	return "DeleteTenantReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTenantReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTenantReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTenantReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTenantReplyValidationError{}

// Validate checks the field values on CheckQuotaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckQuotaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckQuotaRequestMultiError, or nil if none found.
func (m *CheckQuotaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckQuotaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := CheckQuotaRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := QuotaType_name[int32(m.GetQuotaType())]; !ok {
		err := CheckQuotaRequestValidationError{
			field:  "QuotaType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := LimitType_name[int32(m.GetLimitType())]; !ok {
		err := CheckQuotaRequestValidationError{
			field:  "LimitType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ProductCode

	if len(errors) > 0 {
		return CheckQuotaRequestMultiError(errors)
	}

	return nil
}

// CheckQuotaRequestMultiError is an error wrapping multiple validation errors
// returned by CheckQuotaRequest.ValidateAll() if the designated constraints
// aren't met.
type CheckQuotaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckQuotaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckQuotaRequestMultiError) AllErrors() []error { return m }

// CheckQuotaRequestValidationError is the validation error returned by
// CheckQuotaRequest.Validate if the designated constraints aren't met.
type CheckQuotaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckQuotaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckQuotaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckQuotaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckQuotaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckQuotaRequestValidationError) ErrorName() string {
	return "CheckQuotaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckQuotaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckQuotaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckQuotaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckQuotaRequestValidationError{}

// Validate checks the field values on CheckQuotaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckQuotaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckQuotaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckQuotaReplyMultiError, or nil if none found.
func (m *CheckQuotaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckQuotaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQuota()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CheckQuotaReplyValidationError{
					field:  "Quota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CheckQuotaReplyValidationError{
					field:  "Quota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuota()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CheckQuotaReplyValidationError{
				field:  "Quota",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for HasQuota

	// no validation rules for AvailableQuota

	if len(errors) > 0 {
		return CheckQuotaReplyMultiError(errors)
	}

	return nil
}

// CheckQuotaReplyMultiError is an error wrapping multiple validation errors
// returned by CheckQuotaReply.ValidateAll() if the designated constraints
// aren't met.
type CheckQuotaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckQuotaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckQuotaReplyMultiError) AllErrors() []error { return m }

// CheckQuotaReplyValidationError is the validation error returned by
// CheckQuotaReply.Validate if the designated constraints aren't met.
type CheckQuotaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckQuotaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckQuotaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckQuotaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckQuotaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckQuotaReplyValidationError) ErrorName() string { return "CheckQuotaReplyValidationError" }

// Error satisfies the builtin error interface
func (e CheckQuotaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckQuotaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckQuotaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckQuotaReplyValidationError{}

// Validate checks the field values on ConsumeQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConsumeQuotaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsumeQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConsumeQuotaRequestMultiError, or nil if none found.
func (m *ConsumeQuotaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsumeQuotaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := ConsumeQuotaRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := QuotaType_name[int32(m.GetQuotaType())]; !ok {
		err := ConsumeQuotaRequestValidationError{
			field:  "QuotaType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := LimitType_name[int32(m.GetLimitType())]; !ok {
		err := ConsumeQuotaRequestValidationError{
			field:  "LimitType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := ConsumeQuotaRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ProductCode

	// no validation rules for BizId

	// no validation rules for BizType

	if len(errors) > 0 {
		return ConsumeQuotaRequestMultiError(errors)
	}

	return nil
}

// ConsumeQuotaRequestMultiError is an error wrapping multiple validation
// errors returned by ConsumeQuotaRequest.ValidateAll() if the designated
// constraints aren't met.
type ConsumeQuotaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsumeQuotaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsumeQuotaRequestMultiError) AllErrors() []error { return m }

// ConsumeQuotaRequestValidationError is the validation error returned by
// ConsumeQuotaRequest.Validate if the designated constraints aren't met.
type ConsumeQuotaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsumeQuotaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsumeQuotaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsumeQuotaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsumeQuotaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsumeQuotaRequestValidationError) ErrorName() string {
	return "ConsumeQuotaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConsumeQuotaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsumeQuotaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsumeQuotaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsumeQuotaRequestValidationError{}

// Validate checks the field values on ConsumeQuotaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConsumeQuotaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsumeQuotaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConsumeQuotaReplyMultiError, or nil if none found.
func (m *ConsumeQuotaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsumeQuotaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for RemainingQuota

	// no validation rules for Message

	if len(errors) > 0 {
		return ConsumeQuotaReplyMultiError(errors)
	}

	return nil
}

// ConsumeQuotaReplyMultiError is an error wrapping multiple validation errors
// returned by ConsumeQuotaReply.ValidateAll() if the designated constraints
// aren't met.
type ConsumeQuotaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsumeQuotaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsumeQuotaReplyMultiError) AllErrors() []error { return m }

// ConsumeQuotaReplyValidationError is the validation error returned by
// ConsumeQuotaReply.Validate if the designated constraints aren't met.
type ConsumeQuotaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsumeQuotaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsumeQuotaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsumeQuotaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsumeQuotaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsumeQuotaReplyValidationError) ErrorName() string {
	return "ConsumeQuotaReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ConsumeQuotaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsumeQuotaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsumeQuotaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsumeQuotaReplyValidationError{}

// Validate checks the field values on ReleaseQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReleaseQuotaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseQuotaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseQuotaRequestMultiError, or nil if none found.
func (m *ReleaseQuotaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseQuotaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := ReleaseQuotaRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := QuotaType_name[int32(m.GetQuotaType())]; !ok {
		err := ReleaseQuotaRequestValidationError{
			field:  "QuotaType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := LimitType_name[int32(m.GetLimitType())]; !ok {
		err := ReleaseQuotaRequestValidationError{
			field:  "LimitType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := ReleaseQuotaRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ProductCode

	// no validation rules for BizId

	if len(errors) > 0 {
		return ReleaseQuotaRequestMultiError(errors)
	}

	return nil
}

// ReleaseQuotaRequestMultiError is an error wrapping multiple validation
// errors returned by ReleaseQuotaRequest.ValidateAll() if the designated
// constraints aren't met.
type ReleaseQuotaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseQuotaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseQuotaRequestMultiError) AllErrors() []error { return m }

// ReleaseQuotaRequestValidationError is the validation error returned by
// ReleaseQuotaRequest.Validate if the designated constraints aren't met.
type ReleaseQuotaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseQuotaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseQuotaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseQuotaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseQuotaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseQuotaRequestValidationError) ErrorName() string {
	return "ReleaseQuotaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseQuotaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseQuotaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseQuotaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseQuotaRequestValidationError{}

// Validate checks the field values on ReleaseQuotaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ReleaseQuotaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseQuotaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseQuotaReplyMultiError, or nil if none found.
func (m *ReleaseQuotaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseQuotaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for RemainingQuota

	// no validation rules for Message

	if len(errors) > 0 {
		return ReleaseQuotaReplyMultiError(errors)
	}

	return nil
}

// ReleaseQuotaReplyMultiError is an error wrapping multiple validation errors
// returned by ReleaseQuotaReply.ValidateAll() if the designated constraints
// aren't met.
type ReleaseQuotaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseQuotaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseQuotaReplyMultiError) AllErrors() []error { return m }

// ReleaseQuotaReplyValidationError is the validation error returned by
// ReleaseQuotaReply.Validate if the designated constraints aren't met.
type ReleaseQuotaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseQuotaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseQuotaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseQuotaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseQuotaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseQuotaReplyValidationError) ErrorName() string {
	return "ReleaseQuotaReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseQuotaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseQuotaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseQuotaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseQuotaReplyValidationError{}

// Validate checks the field values on ListProductsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProductsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProductsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProductsRequestMultiError, or nil if none found.
func (m *ListProductsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProductsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ListProductsRequestMultiError(errors)
	}

	return nil
}

// ListProductsRequestMultiError is an error wrapping multiple validation
// errors returned by ListProductsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListProductsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProductsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProductsRequestMultiError) AllErrors() []error { return m }

// ListProductsRequestValidationError is the validation error returned by
// ListProductsRequest.Validate if the designated constraints aren't met.
type ListProductsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProductsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProductsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProductsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProductsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProductsRequestValidationError) ErrorName() string {
	return "ListProductsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListProductsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProductsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProductsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProductsRequestValidationError{}

// Validate checks the field values on ListProductsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListProductsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProductsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProductsReplyMultiError, or nil if none found.
func (m *ListProductsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProductsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProductsReplyValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProductsReplyValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProductsReplyValidationError{
					field:  fmt.Sprintf("Products[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListProductsReplyMultiError(errors)
	}

	return nil
}

// ListProductsReplyMultiError is an error wrapping multiple validation errors
// returned by ListProductsReply.ValidateAll() if the designated constraints
// aren't met.
type ListProductsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProductsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProductsReplyMultiError) AllErrors() []error { return m }

// ListProductsReplyValidationError is the validation error returned by
// ListProductsReply.Validate if the designated constraints aren't met.
type ListProductsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProductsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProductsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProductsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProductsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProductsReplyValidationError) ErrorName() string {
	return "ListProductsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListProductsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProductsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProductsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProductsReplyValidationError{}
