// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tenant-service/internal/biz"
	"tenant-service/internal/conf"
	"tenant-service/internal/data"
	"tenant-service/internal/server"
	"tenant-service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	tenantRepo := data.NewTenantRepo(dataData, logger)
	tenantUsecase := biz.NewTenantUsecase(tenantRepo, logger)
	quotaRepo := data.NewQuotaRepo(dataData, logger)
	quotaUsecase := biz.NewQuotaUsecase(quotaRepo, logger)
	productRepo := data.NewProductRepo(dataData, logger)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	tenantService := service.NewTenantService(tenantUsecase, quotaUsecase, productUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, tenantService, logger)
	httpServer := server.NewHTTPServer(confServer, tenantService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
